insert into users
(auth0_id,first_name,last_name,picture,email,current_job,looking_for,preferred_location,current_zipcode,work_history,education_background,bio,active,attachment,industry_code,isApplicant,isRecruiter)
values
('A1184','User1','Last1','https://res.cloudinary.com/djsmw5c9x/image/upload/v1535495464/Products/homer.jpg','homer@simpson.com','Safety Inspector','Any Job','AZ','85077','Springfield Nuclear Plant','BS Nuclear Science','Looking for a company with free food.','true','resume.png','Wireless','true','false'),
('A1185','User2','Last1','https://res.cloudinary.com/djsmw5c9x/image/upload/v1534804405/Products/llgxbftcsdvuytb89jll.png','homer@simpson.com','Safety Inspector','Any Job','AZ','85075','Springfield Nuclear Plant','BS Nuclear Science','Looking for a company with free food.','true','resume.png','Wireless','true','false'),
('A1186','User3','Last1','https://res.cloudinary.com/djsmw5c9x/image/upload/v1534195194/Products/veup0wmoh0k2nhfg8mxo.jpg','homer@simpson.com','Safety Inspector','Any Job','AZ','85076','Springfield Nuclear Plant','BS Nuclear Science','Looking for a company with free food.','true','resume.png','Wireless','true','false'),
('A1187','User4','Last1','https://res.cloudinary.com/djsmw5c9x/image/upload/v1534195080/Products/idgit8tilakwlo48112h.jpg','homer@simpson.com','Safety Inspector','Any Job','AZ','85079','Springfield Nuclear Plant','BS Nuclear Science','Looking for a company with free food.','true','resume.png','Wireless','true','false'),
('A1188','User5','Last1','https://res.cloudinary.com/djsmw5c9x/image/upload/v1534194995/Products/drhcy5met0v6xw3pfckd.jpg','homer@simpson.com','Safety Inspector','Any Job','AZ','85076','Springfield Nuclear Plant','BS Nuclear Science','Looking for a company with free food.','true','resume.png','Wireless','true','false'),
('A1189','User6','Last1','https://res.cloudinary.com/djsmw5c9x/image/upload/v1534194919/Products/x8gttworqd4mhijzspty.jpg','homer@simpson.com','Safety Inspector','Any Job','AZ','85075','Springfield Nuclear Plant','BS Nuclear Science','Looking for a company with free food.','true','resume.png','Writing and Editing','true','false'),
('A1190','User7','Last1','https://res.cloudinary.com/djsmw5c9x/image/upload/v1534194879/Products/l9x4a5zin19atnjsv53d.jpg','homer@simpson.com','Safety Inspector','Any Job','AZ','85077','Springfield Nuclear Plant','BS Nuclear Science','Looking for a company with free food.','true','resume.png','Writing and Editing','true','false'),
('A1191','User8','Last1','https://res.cloudinary.com/djsmw5c9x/image/upload/v1534194843/Products/xluwskbgyvipvvqjfi63.jpg','homer@simpson.com','Safety Inspector','Any Job','AZ','85075','Springfield Nuclear Plant','BS Nuclear Science','Looking for a company with free food.','true','resume.png','Writing and Editing','true','false'),
('R1184','Recruiter3','Last1','https://res.cloudinary.com/djsmw5c9x/image/upload/v1534804405/Products/llgxbftcsdvuytb89jll.png','homer@simpson.com','Safety Inspector','Job ID 21343253: Fulltime','AZ','85075','Springfield Nuclear Plant','BS Nuclear Science','Looking for a company with free food.','true','resume.png','Wireless','false','true'),
('R1185','Recruiter4','Last1','https://res.cloudinary.com/djsmw5c9x/image/upload/v1534194797/Products/eeuxgp3xf10rfunyhwfx.jpg','homer@simpson.com','Safety Inspector','Job ID 21343253: Fulltime','AZ','85079','Springfield Nuclear Plant','BS Nuclear Science','Looking for a company with free food.','true','resume.png','Wireless','false','true'),
('R1186','Recruiter3','Last1','https://res.cloudinary.com/djsmw5c9x/image/upload/v1534804405/Products/llgxbftcsdvuytb89jll.png','homer@simpson.com','Safety Inspector','Job ID 21343253: Fulltime','AZ','85076','Springfield Nuclear Plant','BS Nuclear Science','Looking for a company with free food.','true','resume.png','Wireless','false','true'),
('R1187','Recruiter4','Last1','https://res.cloudinary.com/djsmw5c9x/image/upload/v1534194797/Products/eeuxgp3xf10rfunyhwfx.jpg','homer@simpson.com','Safety Inspector','Job ID 21343253: Fulltime','AZ','85077','Springfield Nuclear Plant','BS Nuclear Science','Looking for a company with free food.','true','resume.png','Wireless','false','true'),
('R1188','Recruiter5','Last1','https://res.cloudinary.com/djsmw5c9x/image/upload/v1534194761/Products/j1696skahk640zdduj1t.jpg','homer@simpson.com','Safety Inspector','Job ID 21343253: Fulltime','AZ','85077','Springfield Nuclear Plant','BS Nuclear Science','Looking for a company with free food.','true','resume.png','Wireless','false','true'),
('R1189','Recruiter6','Last1','https://res.cloudinary.com/djsmw5c9x/image/upload/v1534194710/Products/hqjsdkbn0ocbtoe6ruvu.jpg','homer@simpson.com','Safety Inspector','Job ID 21343253: Fulltime','AZ','85078','Springfield Nuclear Plant','BS Nuclear Science','Looking for a company with free food.','true','resume.png','Writing and Editing','false','true'),
('R1190','Recruiter7','Last1','https://res.cloudinary.com/djsmw5c9x/image/upload/v1534194670/Products/lmoxafif6cztsdp13gb4.jpg','homer@simpson.com','Safety Inspector','Job ID 21343253: Fulltime','AZ','85078','Springfield Nuclear Plant','BS Nuclear Science','Looking for a company with free food.','true','resume.png','Writing and Editing','false','true'),
('R1191','Recruiter8','Last1','https://res.cloudinary.com/djsmw5c9x/image/upload/v1534194619/Products/zvdjy2xd0olakqd5130f.jpg','homer@simpson.com','Safety Inspector','Job ID 21343253: Fulltime','AZ','85077','Springfield Nuclear Plant','BS Nuclear Science','Looking for a company with free food.','true','resume.png','Writing and Editing','false','true')
